### ISSUE TITLE
Support for VM?

### ISSUE THREAD

**Issue by akatsukilevi** [ClarityCafe/maru#15]
Does it supports running on Virtual Machines?
I'm using the pre-built image( got it [Here](https://files.onozuka.info/public/R79-12607.9.2019_11_05_2033-a1.bin.xz) ).
It boots to Grub, but no matter the option i select it completely hangs up.
Should i compile it from source instead(if yes any distro work or should i get a specific one)?

**Comment by sr229** [comment]
@akatsukilevi we already added support upstream but I haven't had someone to build the OS at this moment (we kinda lack funding so we can't run our own gigantic Jenkins, builds are done by volunteers).

**Comment by akatsukilevi** [comment]
I can compile it, just need wait my new SSD to arrive so i can install Linux on it(running on Windows here XD).

**Comment by sr229** [comment]
VM should be supported now, if it doesn't work, let me know.
